name: tb_variant_filter_dev
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
    - pytest >=4.3.1
    - tox
    - flake8
    - black
    - intervaltree
    - lxml
    - pandas
    - vcfpy
    - requests
    - py2neo >=4.2.0
