name: tb_variant_filter_dev
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
    - pytest >=6
    - tox
    - flake8
    - black
    - intervaltree
    - lxml
    - pandas
    - vcfpy
    - requests
    - twine >=3.4.1
    - build
    - py2neo >=4.2.0
