version: 2

jobs:
  build:
    working_directory: ~/tb_variant_filter
    docker:
      - image: continuumio/miniconda3
    steps:
      - checkout

      - restore_cache:
          - keys:
              - tb_variant_filter-{{ checksum "conda_requirements.txt" }}


      - run:
          command: |
            conda config --add channels conda-forge
            conda config --add bioconda
            conda install --file conda_requirements.txt

      - save_cache:
          key: tb_variant_filter-{{ checksum "conda_requirements.txt" }}

      - run: python -m pytest