categories:
  - Variant Analysis
description: M. tuberculosis H37Rv VCF filter
homepage_url: https://github.com/pvanheus/tb_variant_filter
long_description: |
  This tool offers multiple options for filtering variants (in
  VCF files, relative to M. tuberculosis H37Rv).
name: tb_variant_filter
owner: sanbi-uwc
remote_repository_url: https://github.com/pvanheus/tb_variant_filter
type: unrestricted